version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo [PHASE] Entered the build phase...
      - gradle bootjar
  post_build:
    commands:
      - echo [PHASE] Entered the post_build phase...
      - echo $(basename ./build/libs/*.jar)
      - ls -al
      - chmod +x scripts/deploy_dev.sh
artifacts:
  files:
    - deploy/dev/appspec.yml
    - build/libs/*.jar
    - scripts/deploy_dev.sh
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
