eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9020/eureka/}
    register-with-eureka: true
    fetch-registry: true

---
spring:
  profiles: local

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9020/eureka/}
    register-with-eureka: true
    fetch-registry: true

---
spring:
  profiles: sta

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka:9020/eureka/}
    register-with-eureka: true
    fetch-registry: true
